services:
  db:
    extends:
      file: ./echo/docker-compose.yml
      service: db

  valkey:
    extends:
      file: ./echo/docker-compose.yml
      service: valkey

  echo:
    extends:
      file: ./echo/docker-compose.yml
      service: app
    ports:
      - "8080:8080"

  oriana:
    extends:
      file: ./oriana/docker-compose.yml
      service: app
    networks:
      - backend
    depends_on:
      - echo

networks:
  backend:

volumes:
  postgres_data:
